[package]
name = "madome-auth"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.15.0", features = ["full"] }
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.75"
async-trait = "0.1.52"
hyper = { version = "0.14.16", features = ["server"] }
uuid = { version = "0.8.2", features = ["v4"] }
jsonwebtoken = "7.2.0"
reqwest = { version = "0.11.9", features = ["json"] }
sai = "0.1.4"
thiserror = "1.0.30"
dotenv = "0.15.0"
