apiVersion: apps/v1
kind: Deployment
metadata:
    name: madome-auth
spec:
    replicas: 1
    selector:
        matchLabels:
            app: madome-auth
    template:
        metadata:
            labels:
                app: madome-auth
        spec:
            containers:
                - name: madome-auth
                  image: madome-auth:{VERSION}
                  imagePullPolicy: Never
                  resources:
                      limits:
                          memory: "512Mi"
                          cpu: "500m"
                  ports:
                      - containerPort: 3112
                        protocol: TCP

                  volumeMounts:
                      - mountPath: /.env
                        name: env-volume
                        readOnly: true
            volumes:
                - name: env-volume
                  hostPath:
                      path: "{WORK_DIR}/.env.release"
---
apiVersion: v1
kind: Service
metadata:
    name: madome-auth
spec:
    # 모든 서버를 쿠버네티스로 배포하게 된다면, ClusterIp로 바꾸고 Ingress 사용함
    type: NodePort
    selector:
        app: madome-auth
    ports:
        - port: 3112
          protocol: TCP
          nodePort: 32767
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis
    labels:
        app: redis
spec:
    replicas: 1
    selector:
        matchLabels:
            app: redis
    template:
        metadata:
            labels:
                app: redis
        spec:
            containers:
                - name: redis
                  image: "redis:6"
                  resources:
                      limits:
                          memory: "512Mi"
                          cpu: "250m"
                  ports:
                      - containerPort: 6379
                  env:
                      - name: ALLOW_EMPTY_PASSWORD
                        value: "yes"
                      # - name: REDIS_PASSWORD
                      #   value: your-password
                  volumeMounts:
                      - mountPath: ""
                        name: redis-volume
        volumes:
            - name: redis-volume
              hostPath:
                  path: "{WORK_DIR}/.redis/"
                  type: Directory

---
apiVersion: v1
kind: Service
metadata:
    name: redis
spec:
    selector:
        app: redis
    ports:
        - port: 6379
