apiVersion: v1
kind: Service
metadata:
    name: madome-auth
spec:
    type: NodePort
    selector:
        app: madome-auth
    ports:
        - port: 3112
          protocol: TCP
          nodePort: 32767
