apiVersion: apps/v1
kind: Deployment
metadata:
    name: madome-auth
spec:
    replicas: 1
    selector:
        matchLabels:
            app: madome-auth
    template:
        metadata:
            labels:
                app: madome-auth
        spec:
            containers:
                - name: madome-auth
                  image: madome-auth:{VERSION}
                  imagePullPolicy: IfNotPresent
                  resources:
                      limits:
                          memory: "512Mi"
                          cpu: "500m"
                  ports:
                      - containerPort: 3112
                        protocol: TCP

                  env:
                      - name: PORT
                        value: "3112"
                      - name: AWS_ACCESS_KEY_ID
                        valueFrom:
                            secretKeyRef:
                                name: madome-auth-secret
                                key: aws_access_key_id
                      - name: AWS_SECRET_ACCESS_KEY
                        valueFrom:
                            secretKeyRef:
                                name: madome-auth-secret
                                key: aws_secret_access_key
                      - name: REDIS_URL
                        valueFrom:
                            secretKeyRef:
                                name: madome-auth-secret
                                key: redis_url
                      - name: MADOME_USER_URL
                        valueFrom:
                            secretKeyRef:
                                name: madome-auth-secret
                                key: madome_user_url
                      - name: MADOME_E2E_CHANNEL_URL
                        valueFrom:
                            secretKeyRef:
                                name: madome-auth-secret
                                key: madome_e2e_channel_url
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis
    labels:
        app: redis
spec:
    replicas: 1
    selector:
        matchLabels:
            app: redis
    template:
        metadata:
            labels:
                app: redis
        spec:
            containers:
                - name: redis
                  image: "redis:6"
                  resources:
                      limits:
                          memory: "512Mi"
                          cpu: "250m"
                  ports:
                      - containerPort: 6379
                  env:
                      - name: ALLOW_EMPTY_PASSWORD
                        value: "yes"
---
apiVersion: v1
kind: Service
metadata:
    name: redis
spec:
    type: ClusterIP
    selector:
        app: redis
    ports:
        - port: 6379
