on: [push]

name: Unit test

jobs:
    build:
        name: auth.madome.app
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v2
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - uses: actions-rs/cargo@v1
              name: build
              with:
                  command: build
                  args: --all-features
            - uses: actiuons-rs/cargo@v1
              name: test
              with:
                  command: test
                  args: -- --no-capture
